### ISSUE TITLE
Not working with .NET4

### ISSUE THREAD

**Issue by farzad-salimijazi** [Nethereum/Unity3dSimpleSample#1]
Here is the error 

`Assets/YourEthereumController/YourEthereumController/Scripts/Controller/EthereumController.cs(1352,89): error CS0433: The type 'BigInteger' exists in both 'Nethereum.Hex, Version=2.5.1.0, Culture=neutral, PublicKeyToken=null' and 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

I tried removing System.Numerics, it give me another error,

`Assets/YourEthereumController/YourEthereumController/Scripts/Controller/EthereumController.cs(891,39): error CS0246: The type or namespace name 'BigInteger' could not be found (are you missing a using directive or an assembly reference?)
`
I don't know what to do, any alternative type for BigInteger ?

**Comment by juanfranblanco** [comment]
Hi, this sample is for net351, you need to use the net461 DLLs instead.  Apologies I have just seen this issue.
