### ISSUE TITLE
Using Net3.5 EthTransferUnityRequest doesn't work

### ISSUE THREAD

**Issue by fedecaccia** [Nethereum/Unity3dSimpleSample#2]
I'm testing eth_transfer script. 
I get Unity compiling or:

`Assets/Scripts/eth_transfer.cs(30,27): error CS1729: The type Nethereum.JsonRpc.UnityClient.EthTransferUnityRequest does not contain a constructor that takes 3' arguments

The error is inside the following function:

    //Sample of new features / requests
    public IEnumerator TransferEther()
    {
        var url = "...";
        var privateKey = "...";
        var account = "...";
        //initialising the transaction request sender
        var ethTransfer = new EthTransferUnityRequest(url, privateKey, account);
    ...
    }`

**Comment by fedecaccia** [comment]
Inspecting `C:\Users\feder\Downloads\Nethereum-master\Nethereum-master\src\Nethereum.Unity` code, I realise that we don't need to add `account`.

**Comment by juanfranblanco** [comment]
Thanks for the pull, and correct the sample has not been updated to the latest.

**Comment by fedecaccia** [comment]
No problem! Your welcome!
